project:
  type: book

book:
  title: "CSC477-Group-4"
  author: "Chris Jacob"
  date: "8/26/2024"
  chapters:
    - index.qmd
    - weekly_updates.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

